AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for the API Service

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment."
  ResourceBaseIdentifier:
    Type: String
    Description: "Base identifier for resource naming."
  CognitoUserPoolId:
    Type: String
    Description: "The ID of the Cognito User Pool used for authentication."
  CognitoUserPoolClientId:
    Type: String
    Description: "The Client ID for the Cognito User Pool used for authentication."
  DynamoDBTableName:
    Type: String
    Description: "The name for the table the API will communicate with."
  DynamoDBTableArn:
    Type: String
    Description: "The ARN for the table the API will communicate with."

Resources:
  ExpenzoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api/
      Handler: main.handler
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          ENV: !Ref Environment
          CERT_SECRET_NAME: expenzo-dev-teller-cert
          PK_SECRET_NAME: expenzo-dev-teller-pk
          DYNAMO_DB_TABLE_NAME: !Ref DynamoDBTableName
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_APP_CLIENT_ID: !Ref CognitoUserPoolClientId
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:expenzo-dev-teller-cert-*
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:expenzo-dev-teller-pk-*
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Ref DynamoDBTableArn
      Events:
        ExpenzoApiGet:
          Type: Api
          Properties:
            Path: /accounts
            Method: GET
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: CognitoAuthorizer
        ExpenzoApiPost:
          Type: Api
          Properties:
            Path: /accounts
            Method: POST
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: CognitoAuthorizer

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'http://localhost:3000'"
        MaxAge: "'600'"
        AllowCredentials: true
      Auth:
        AddDefaultAuthorizerToCorsPreflight: False
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
            IdentitySource: "method.request.header.Authorization"
            ValidationExpression: "^Bearer [A-Za-z0-9-_=.]+$"

Outputs:
  ApiUrl:
    Description: "URL of the API"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/accounts"
